### ISSUE TITLE
Unable to use this with branches

### ISSUE THREAD

**Issue by deveshkp** [ODMDev/odm-transformation-advisor#3]
Hi there,

The current version only works with main branch, and we have lot of projects which have branches. So I am submitting this enhancement request for adding branch feature in OTA.

Thx

**Comment by pberlandier** [comment]
Updated with the ability to specify a target branch along with the projects selected through the ota.projects parameter.
https://github.com/ODMDev/odm-transformation-advisor/releases/tag/v1.0.1
